### ISSUE TITLE
Potential bug in lcd.py

### ISSUE THREAD

**Issue by JPFrancoia** [jeffmer/micropython-ili9341#4]
Hi,

Great library, it works smoothly with my ESP32 and my TFT screen.

I noticed that the `data` variable is undefined on this line: https://github.com/jeffmer/micropython-ili9341/blob/539b0a1198d766901e5b4b118b1b6a706ea1a35d/ili934xnew.py#L189.

Maybe the function defintion should be:

```python
def _readblock(self, x0, y0, x1, y1, data=None):
```

If that's the case and if this repo is not dead, I can make a PR.

Cheers! Thanks for your work

**Comment by jeffmer** [comment]
I think you are right. I am not sure I ever used this function, happy to accept your PR. 

Thanks,

Jeff

**Comment by JPFrancoia** [comment]
Done!

**Comment by JPFrancoia** [comment]
Merged, closing. Thanks!
