### ISSUE TITLE
Pins to use for a TTGO T8 v1.7

### ISSUE THREAD

**Issue by aguaviva** [jeffmer/micropython-ili9341#7]
I got your code working on a TTGO T8 v1.7
It took me a while to figure out which pins to use, so I am posting here the init sequence in case this saves time to other people

```
spi = SPI(2, baudrate=40000000, miso=Pin(19), mosi=Pin(23), sck=Pin(18))
display = ILI9341(pi, cs=Pin(5), dc=Pin(0), rst=Pin(4), w=320, h=240, r=3)
```

Thanks!

**Comment by jeffmer** [comment]
Thanks, I will put this in the ReadMe when I get a chance
